# np.vstack((a,b))

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [4]:
a = np.array([1,2,3,4,5,6,7] )
np.vstack([a for i in range(7)])#重复7次vstack

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

# np.empty([m,n],dtype=)

In [5]:
np.empty([2, 2], dtype=int)

array([[ 94674786267424,               0],
       [             32, 140056565394048]])

In [6]:
np.empty([2, 2], dtype=np.float64)

array([[4.67755544e-310, 0.00000000e+000],
       [6.91971410e-310, 0.00000000e+000]])

# np.empty_like(a)

In [7]:
a = ([1,2,3], [4,5,6])                         # a is array-like
np.empty_like(a)

array([[94674780527024,              0,              0],
       [             0,              0,              0]])

# np.random.permutation

In [8]:
np.random.permutation(10)

array([2, 0, 3, 6, 8, 5, 7, 4, 1, 9])

In [9]:
np.random.permutation([1, 4, 9, 12, 15])

array([15,  9, 12,  4,  1])

In [10]:
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# enumerate(a)

In [11]:
seasons = [[1, 2], [3, 4]]
a = [[1,2],[3,4]]
[(i,j)for i ,j in enumerate(seasons)]

[(0, [1, 2]), (1, [3, 4])]

In [12]:
pop = np.vstack([np.random.permutation(10) for _ in range(10)])
city_position = np.random.randint(1,3,[10,2])

In [13]:
for i, d in enumerate(pop):
    b = city_position[d]
    print(b)
    print([d])

[[1 2]
 [1 1]
 [1 1]
 [2 1]
 [1 2]
 [1 2]
 [2 2]
 [1 1]
 [1 2]
 [1 2]]
[array([2, 1, 3, 7, 5, 9, 4, 0, 8, 6])]
[[1 2]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [1 2]
 [2 2]
 [2 1]]
[array([5, 8, 1, 3, 0, 9, 2, 6, 4, 7])]
[[1 1]
 [1 2]
 [1 2]
 [1 2]
 [1 1]
 [2 1]
 [1 2]
 [2 2]
 [1 2]
 [1 1]]
[array([3, 6, 5, 2, 0, 7, 8, 4, 9, 1])]
[[1 2]
 [2 1]
 [1 1]
 [1 2]
 [2 2]
 [1 2]
 [1 1]
 [1 2]
 [1 2]
 [1 1]]
[array([8, 7, 3, 9, 4, 5, 0, 6, 2, 1])]
[[2 1]
 [1 2]
 [1 2]
 [2 2]
 [1 2]
 [1 1]
 [1 2]
 [1 1]
 [1 2]
 [1 1]]
[array([7, 5, 2, 4, 6, 1, 8, 3, 9, 0])]
[[1 2]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [2 1]
 [1 2]
 [1 1]
 [2 2]
 [1 2]]
[array([6, 5, 9, 3, 1, 7, 8, 0, 4, 2])]
[[1 1]
 [1 2]
 [1 2]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [1 2]
 [2 1]
 [1 2]]
[array([1, 6, 8, 0, 2, 4, 3, 5, 7, 9])]
[[1 2]
 [1 2]
 [2 2]
 [1 2]
 [1 2]
 [1 2]
 [1 1]
 [2 1]
 [1 1]
 [1 1]]
[array([2, 9, 4, 5, 8, 6, 3, 7, 1, 0])]
[[1 1]
 [2 2]
 [2 1]
 [1 2]
 [1 2]
 [1 1]
 [1 2]
 [1 1]
 [1 2]
 [1 2]]
[array([1, 4, 7, 9, 5, 0, 6, 3, 2, 8])]
[

# zip(a,b)

In [14]:
a = [[1,2,3],[4,5,6]]
b = [4,5,6]
c = [4,5,6,7,8]
list(zip(b,b))

[(4, 4), (5, 5), (6, 6)]

In [15]:
list(zip(a,a))

[([1, 2, 3], [1, 2, 3]), ([4, 5, 6], [4, 5, 6])]

# np.diff(x)

In [16]:
x = np.array([1,2,4,8])
np.square(np.diff(x))#计算下一个数到上一个数字的差

array([ 1,  4, 16])

# np.isin() 

In [17]:
element = 2*np.arange(4).reshape((2, 2))
element

array([[0, 2],
       [4, 6]])

In [18]:
test_elements = [1, 2, 4, 8]
mask = np.isin(element, test_elements)
mask

array([[False,  True],
       [ True, False]])

In [19]:
test_elements = [1, 2, 4, 8]
mask = np.isin(element, test_elements,invert = True)
mask

array([[ True, False],
       [False,  True]])

# np.ravel()

In [20]:
x = np.array([[2,2,1], [4, 5, 6]])
x.ravel()

array([2, 2, 1, 4, 5, 6])

In [21]:
x.ravel(order = 'K')

array([2, 2, 1, 4, 5, 6])

In [22]:
x.ravel(order = 'C')

array([2, 2, 1, 4, 5, 6])

In [23]:
x.ravel(order = 'F')

array([2, 4, 2, 5, 1, 6])

In [24]:
x.ravel(order = 'A')

array([2, 2, 1, 4, 5, 6])

# np.flatten()

In [25]:
x = np.array([[2,2,1], [4, 5, 6]])
x.flatten()

array([2, 2, 1, 4, 5, 6])

# numpy.concatenate（a,b）

In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [28]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

# numpy.choice()

In [29]:
idx = np.random.choice(np.arange(10),size = 10,replace=True)
idx

array([3, 5, 6, 5, 7, 2, 4, 9, 8, 4])

In [30]:
x = [[1,2,5],[3,4,1]]
y = [[5,2,1],[9,5,1]]
z = np.diff(x)

In [31]:
x[1] = [1,2,3]

In [32]:
x

[[1, 2, 5], [1, 2, 3]]

In [33]:
np.random.rand()

0.8155382142298284

In [34]:
x = z[1]

In [35]:
x

array([ 1, -3])

In [36]:
line_x = [[1,2],[3,4]]
line_y = [[5,6],[7,8]]
for i, (xs, ys) in enumerate(zip(line_x, line_y)):
    print(xs)

[1, 2]
[3, 4]


In [37]:
list(zip(line_x, line_y))

[([1, 2], [5, 6]), ([3, 4], [7, 8])]

In [38]:
sqrt = np.diff(line_x)+np.diff(line_y)

In [39]:
sqrt

array([[2],
       [2]])

In [40]:
 np.empty((np.array(line_x).shape[0]), dtype=np.float64)

array([5.e-324, 5.e-324])

# np取值

In [41]:
x =np.array([[1,2,3],[4,5,6],[7,8,9]]).astype(np.bool_)
y =np.array([[2,3,4],[5,6,7]])

In [42]:
z = x[[0,2]]
z

array([[ True,  True,  True],
       [ True,  True,  True]])

In [43]:
x[[0,2]] = y

In [44]:
x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [45]:
x[:,0]

array([ True,  True,  True])

In [46]:
x[1,2]

True

In [47]:
x[(1,2),2]

array([ True,  True])

In [48]:
x[[1,2],2]

array([ True,  True])

# bool

In [49]:
x = np.random.randint(0,2,size = [10]).astype(np.bool_)

In [50]:
x

array([False,  True, False,  True, False,  True, False,  True,  True,
       False])

In [51]:
y = np.array([1,2,3,4,5,6,7,8,9,10])
z = np.array([11,12,13,14,15,16,17,18,19,20])

In [52]:
y[x] = z[x]

In [53]:
y

array([ 1, 12,  3, 14,  5, 16,  7, 18, 19, 10])

In [54]:
z

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
np.random.seed(2)

In [56]:
np.random.randint(0,2)

0

# np.where()

In [57]:
z

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
np.where(z>15)#返回符合条件的索引

(array([5, 6, 7, 8, 9]),)

In [59]:
np.where(z>15,'yes','no')#符合条件输出yes 不符合no

array(['no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes'],
      dtype='<U3')

# 文件操作

## np.load()

In [77]:
a = np.load('/home/zhx/push/dirname.npz',allow_pickle=True) #如果allow_pickle=false 就不能获得数据

In [73]:
a.files

['image_dir']

In [78]:
# print(a['image_dir'])

In [85]:
b = np.load('/home/zhx/push/data/run_02/pose.npy')

In [86]:
b

array([[ 100.        , -132.        ,   -0.52924931],
       [  97.        , -137.        ,   -0.48371753],
       [  97.        , -141.        ,   -0.54979634],
       [  93.        , -145.        ,   -0.50740314]])