In [1]:
import torch

# 数据类型

## type检查

In [2]:
a = torch.randn(2,3)#初始化为2行3列的正态分布矩阵

In [3]:
a.type()

'torch.FloatTensor'

In [4]:
type(a)

torch.Tensor

In [5]:
isinstance(a,torch.FloatTensor)

True

In [6]:
#a = a.cuda()#把tensor放在gpu

## tensor生成

In [7]:
torch.tensor(1.0)#生成tensor标量

tensor(1.)

In [8]:
torch.tensor(1.3)

tensor(1.3000)

## 生成随机序列

In [9]:
torch.randperm(10)

tensor([4, 7, 6, 8, 9, 1, 2, 0, 5, 3])

## dim

In [10]:
a = torch.tensor(2.2)
a.shape

torch.Size([])

In [11]:
a.size()

torch.Size([])

In [12]:
torch.tensor([1.1])

tensor([1.1000])

In [13]:
torch.tensor([1.1,1.2])

tensor([1.1000, 1.2000])

In [14]:
torch.FloatTensor(1)#生成一个1维度1长度的FloatTensor

tensor([6.4185e-22])

In [15]:
torch.FloatTensor(2)

tensor([6.4185e-22, 4.5674e-41])

In [16]:
import numpy as np
data = np.ones(2)

In [17]:
torch.from_numpy(data)#numpy->tensor

tensor([1., 1.], dtype=torch.float64)

In [18]:
a = torch.randn(2,3)
a

tensor([[ 1.0897,  0.2299,  1.5621],
        [ 0.1376, -1.3806,  0.6868]])

In [19]:
a.shape

torch.Size([2, 3])

In [20]:
a.size(0)

2

In [21]:
a.shape[1]

3

In [22]:
a = torch.rand(1,2,3)

In [23]:
a

tensor([[[0.7904, 0.0943, 0.0452],
         [0.1364, 0.7557, 0.0370]]])

In [24]:
list(a)

[tensor([[0.7904, 0.0943, 0.0452],
         [0.1364, 0.7557, 0.0370]])]

In [25]:
a.shape

torch.Size([1, 2, 3])

In [26]:
list(a.shape)

[1, 2, 3]

# 维度变换

## View and reshape 两者一样

In [27]:
a = torch.rand(4,1,28,28)

In [28]:
a.shape

torch.Size([4, 1, 28, 28])

In [29]:
a = a.view(4,28,28)

In [30]:
a = a.reshape(4,1,28,28)

## squeeze and unsqueeze

In [31]:
a.shape

torch.Size([4, 1, 28, 28])

In [32]:
a.unsqueeze(0).shape#在第0维度增加一个维度

torch.Size([1, 4, 1, 28, 28])

In [33]:
a.squeeze().size()#把所有的1全挤压掉

torch.Size([4, 28, 28])

In [34]:
a.squeeze(0).size()#把第一维度给cut

torch.Size([4, 1, 28, 28])

## expand

In [35]:
a = torch.rand(4,32,14,14)

In [36]:
b = torch.rand(1,32,1,1)

In [37]:
b.expand(4,32,4,4).shape#维度为1的地方可以扩张

torch.Size([4, 32, 4, 4])

In [38]:
b.expand(4,-1,-1,-1).shape#-1表示不变

torch.Size([4, 32, 1, 1])

## repeat

In [39]:
b.repeat(4,2,4,4).shape#表示在每一个维度上复制多少次

torch.Size([4, 64, 4, 4])

## t转置 只适用于dim = 2

In [40]:
a = torch.rand(1,2)

In [41]:
a.t()

tensor([[0.2760],
        [0.8509]])

## transpose
用于交换两个维度

In [42]:
b.transpose(1,3).shape

torch.Size([1, 1, 1, 32])

## permute
多维度交换

In [43]:
b.permute(0,3,2,1).shape

torch.Size([1, 1, 1, 32])

# 合并与分割

## cat合并

In [44]:
a = torch.rand(4,32,8)
b = torch.rand(5,32,8)
torch.cat([a,b],dim=0).shape#把第一维度进行合并，要求其他维度要一样

torch.Size([9, 32, 8])

## stack在新的维度合并

In [45]:
c = torch.rand(4,32,8)
torch.stack([a,c],dim=2).shape#要求维度大小要完全一致

torch.Size([4, 32, 2, 8])

## split 拆分
按一组大小多少拆分

In [46]:
aa,bb = c.split([1,3],dim=0)

In [47]:
aa.shape,bb.shape

(torch.Size([1, 32, 8]), torch.Size([3, 32, 8]))

In [48]:
aa,bb = c.split(2,dim=0)#2表示拆分成2个长度为一组，不是拆分成几组哦

In [49]:
aa,bb,cc,dd = c.split(1,dim=0)#1个长度为一组，一共四组

## chunk拆分 
按多少组拆分

In [50]:
aa,bb,cc,dd = c.chunk(4,dim=0)

In [51]:
aa.shape,bb.shape,cc.shape,dd.shape

(torch.Size([1, 32, 8]),
 torch.Size([1, 32, 8]),
 torch.Size([1, 32, 8]),
 torch.Size([1, 32, 8]))

## unbind

In [52]:
a = c.unbind(axis=0)#按照第一维度，直接打散

In [53]:
a[0].shape

torch.Size([32, 8])

# 数学计算

## + - * /

In [54]:
a = torch.randn(3,4)
b = torch.rand(4)

In [55]:
a+b

tensor([[ 0.6461, -1.0801, -0.7438,  1.4101],
        [ 0.4190,  1.9347,  2.4019,  0.4772],
        [ 1.0521,  0.9325,  0.8409,  2.3151]])

In [56]:
torch.add(a,b)

tensor([[ 0.6461, -1.0801, -0.7438,  1.4101],
        [ 0.4190,  1.9347,  2.4019,  0.4772],
        [ 1.0521,  0.9325,  0.8409,  2.3151]])

In [57]:
torch.all(torch.eq(a-b,torch.sub(a,b)))#or就是与运算符，判断是否所有的a-b sub(a,b)计算结果相等

tensor(True)

In [58]:
torch.all(torch.eq(a*b,torch.mul(a,b)))

tensor(True)

In [59]:
torch.all(torch.eq(a/b,torch.div(a,b)))#//表示整除

tensor(True)

## 矩阵乘法

In [60]:
a = 3*torch.ones([2,2])
b = 2*torch.ones([2,2])
a,b

(tensor([[3., 3.],
         [3., 3.]]),
 tensor([[2., 2.],
         [2., 2.]]))

In [61]:
a@b

tensor([[12., 12.],
        [12., 12.]])

In [62]:
torch.matmul(a,b)

tensor([[12., 12.],
        [12., 12.]])

In [63]:
a*b#*仅仅表示对应位置的元素相乘

tensor([[6., 6.],
        [6., 6.]])

## power 次方

In [64]:
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [65]:
a**2

tensor([[9., 9.],
        [9., 9.]])

In [66]:
a.sqrt()

tensor([[1.7321, 1.7321],
        [1.7321, 1.7321]])

In [67]:
a**0.5

tensor([[1.7321, 1.7321],
        [1.7321, 1.7321]])

## exp()

In [68]:
torch.exp(torch.ones(2,2))

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

## 取整数取小数

In [69]:
a = torch.tensor(-3.14)

In [70]:
a.floor()#向下取整

tensor(-4.)

In [71]:
a.ceil()#向上取整

tensor(-3.)

In [72]:
a.trunc()#裁剪整数部分

tensor(-3.)

In [73]:
a.frac()#裁剪小数部分

tensor(-0.1400)

In [74]:
b = torch.tensor(4.5)
a.round()#四舍五入 偶数.5舍,奇数.5入
b.round()

tensor(4.)

## 数据最大最小值的裁剪 clamp

In [75]:
grad = torch.rand(2,3)*15
grad

tensor([[ 8.6572,  8.3627,  7.4296],
        [ 0.6315, 13.3095,  2.4311]])

In [76]:
grad.max(),grad.median()#中位数,grad.mean()

(tensor(13.3095), tensor(7.4296))

In [77]:
grad.clamp(10)#小于10的部分都变成10

tensor([[10.0000, 10.0000, 10.0000],
        [10.0000, 13.3095, 10.0000]])

In [78]:
grad.clamp(5,10)#小于5的变5，小于10的变10

tensor([[ 8.6572,  8.3627,  7.4296],
        [ 5.0000, 10.0000,  5.0000]])

# 数据统计

## norm n范数

In [79]:
a = torch.full([2,2,2],2.)

In [80]:
a.norm(1),a.norm(2)

(tensor(16.), tensor(5.6569))

In [81]:
a.norm(1,dim=1)#求第一维度一范数

tensor([[4., 4.],
        [4., 4.]])

## mean sum min max prod

In [82]:
a = torch.arange(8).view(2,4).float()
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [83]:
a.min(),a.max(),a.mean(),a.prod()#最小值、最大值、平均值、所有数字的累乘                                          

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.))

In [84]:
a.argmax(),a.argmin()#所有数据打平，求最大最小值索引

(tensor(7), tensor(0))

In [85]:
a.argmax(dim=1)#在每列上求最大值，记住最终的结果会把数据所求的维度打平

tensor([3, 3])

## dim keepdim

In [86]:
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [87]:
a.max(dim=1)

torch.return_types.max(
values=tensor([3., 7.]),
indices=tensor([3, 3]))

In [88]:
print(a.max(dim=1,keepdim=True))#keepdim在求得最值后，本来对应的维度会变成1而squeeze消失，这个参数可以让dim=1

torch.return_types.max(
values=tensor([[3.],
        [7.]]),
indices=tensor([[3],
        [3]]))


## topk kthvalue 取第几大小的数据

In [89]:
a.topk(3,dim=1).values#算出每一个维度中最大三个数

tensor([[3., 2., 1.],
        [7., 6., 5.]])

In [90]:
a.kthvalue(2,dim=1)#表示第2小的数据

torch.return_types.kthvalue(
values=tensor([1., 5.]),
indices=tensor([1, 1]))

## 比较 

In [91]:
a>0

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True]])

In [92]:
torch.gt(a,0)#和>一个意思

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True]])

In [93]:
a!= 0

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True]])

In [94]:
a = torch.ones(2,3)
b = torch.randn(2,3)

In [95]:
torch.eq(a,b)

tensor([[False, False, False],
        [False, False, False]])

In [96]:
torch.equal(a,b)#全部的值是否相等

False

In [97]:
torch.eq(a,a)

tensor([[True, True, True],
        [True, True, True]])

In [98]:
torch.equal(a,a)

True

# 高级操作

## where(condition,x,y)

In [99]:
condition = torch.rand([4,5])
condition

tensor([[0.6868, 0.6417, 0.5790, 0.4368, 0.8512],
        [0.5429, 0.4583, 0.7274, 0.3485, 0.5018],
        [0.3829, 0.7177, 0.6357, 0.6017, 0.4079],
        [0.8747, 0.6588, 0.4885, 0.5675, 0.0234]])

In [100]:
condition<0.5

tensor([[False, False, False,  True, False],
        [False,  True, False,  True, False],
        [ True, False, False, False,  True],
        [False, False,  True, False,  True]])

In [101]:
x = torch.full([4,5],1)

In [102]:
y = torch.full([4,5],0)

In [103]:
torch.where(condition<0.5,x,y)

tensor([[0, 0, 0, 1, 0],
        [0, 1, 0, 1, 0],
        [1, 0, 0, 0, 1],
        [0, 0, 1, 0, 1]])

In [192]:
def func(n): 
    return n
np.where(condition<0.5, func(n = n+1), 0)

array([[0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1],
       [0, 0, 1, 0, 1]])

## gather 按照索引获得对应的值

In [104]:
label = torch.rand([4,10])
label

tensor([[0.0028, 0.8733, 0.2279, 0.1383, 0.2314, 0.2029, 0.9993, 0.0943, 0.5632,
         0.6487],
        [0.7499, 0.6605, 0.9943, 0.7438, 0.7713, 0.9774, 0.3206, 0.5096, 0.5069,
         0.4043],
        [0.6490, 0.3405, 0.1312, 0.1297, 0.6968, 0.1637, 0.7328, 0.1154, 0.1856,
         0.7503],
        [0.8424, 0.3912, 0.8160, 0.5552, 0.8877, 0.1659, 0.2736, 0.1802, 0.3697,
         0.4345]])

In [107]:
top3 = label.topk(3,dim=1)
idx = top3[1]
idx.shape
idx

tensor([[6, 1, 9],
        [2, 5, 4],
        [9, 6, 4],
        [4, 0, 2]])

In [106]:
torch.gather(label,dim=1,index = idx)

tensor([[0.9993, 0.8733, 0.6487],
        [0.9943, 0.9774, 0.7713],
        [0.7503, 0.7328, 0.6968],
        [0.8877, 0.8424, 0.8160]])

In [169]:
a = torch.rand([2,1,10,10])
b = torch.tensor([[1,2,3,4],[2,3,4,5]])
a

tensor([[[[0.9285, 0.7632, 0.1936, 0.7332, 0.3281, 0.2554, 0.3664, 0.4041,
           0.5436, 0.2830],
          [0.6673, 0.4341, 0.3510, 0.1438, 0.6224, 0.3752, 0.5640, 0.6432,
           0.1457, 0.4139],
          [0.8297, 0.8659, 0.0178, 0.5773, 0.3391, 0.0094, 0.9944, 0.8672,
           0.9777, 0.7757],
          [0.4099, 0.3422, 0.8061, 0.4656, 0.2154, 0.3890, 0.2359, 0.6629,
           0.8639, 0.5241],
          [0.8757, 0.1662, 0.6354, 0.0223, 0.1603, 0.6071, 0.9387, 0.9595,
           0.7719, 0.9767],
          [0.1972, 0.4730, 0.3118, 0.7788, 0.2980, 0.2822, 0.4207, 0.1863,
           0.3878, 0.7676],
          [0.7835, 0.0942, 0.2971, 0.4366, 0.4185, 0.6258, 0.7276, 0.1804,
           0.4380, 0.4697],
          [0.4795, 0.7170, 0.3062, 0.4555, 0.8382, 0.3848, 0.2636, 0.4490,
           0.0983, 0.0409],
          [0.1717, 0.4954, 0.2297, 0.7115, 0.9023, 0.6556, 0.0194, 0.8228,
           0.6108, 0.6997],
          [0.8093, 0.0733, 0.0196, 0.0879, 0.2277, 0.9271, 0.6170, 0.0240

In [170]:
c = torch.tensor([int(b[i,0]) for i in range(2)])
c = c.unsqueeze(1).unsqueeze(2).unsqueeze(3).expand(2,1,1,10)
d = torch.tensor([int(b[i,1]) for i in range(2)])
d = d.unsqueeze(1).unsqueeze(2).unsqueeze(3).expand(2,1,1,1)
c.shape,d.shape

(torch.Size([2, 1, 1, 10]), torch.Size([2, 1, 1, 1]))

In [171]:
a = torch.gather(a, dim=2, index=c)
a.shape
a = torch.gather(a, dim=3, index=d)

In [172]:
a.squeeze(),a.shape

(tensor([0.3510, 0.3722]), torch.Size([2, 1, 1, 1]))

# item

In [11]:
a = torch.Tensor(1,1)


In [12]:
a

tensor([[-7.7060e-37]])

In [13]:
a.item()

-7.70600257839469e-37